### ISSUE TITLE
Installation issue if voluptus is not installed yet

### ISSUE THREAD

**Issue by ludusrusso** [ludusrusso/flask_voluptuous#2]

**Comment by vencik** [comment]
Hello,

I think the issue should be easily mitigated by one of the mechanisms described here:
https://packaging.python.org/guides/single-sourcing-package-version/

I'd go for setting it in `setup.cfg` (as I think that we can safely assume setuptools 46.4.0 by now, see the 1st note).
What do you think? Do you need a hand? I can send a PR...

(BTW, the same applies if Flask is not installed yet, of course...)

vencik

**Comment by vencik** [comment]
Note that PR https://github.com/ludusrusso/flask_voluptuous/pull/3 deals with the issue.

**Comment by ludusrusso** [comment]
fixed in #3
